### ISSUE TITLE
How to use wlpinyin?

### ISSUE THREAD

**Issue by dianhenglau** [xhebox/wlpinyin#1]
Hi. I have managed to compile and run `wlpinyin`:

```
$ ./wlpinyin
[../pinyin_engine.c:24] context_obj: 0x5634a92acef0, sess: 0, msgtype: deploy, msg: start
[../pinyin_engine.c:24] context_obj: 0x5634a92acef0, sess: 0, msgtype: deploy, msg: success
[../pinyin_engine.c:102] schema_name: 朙月拼音, id: luna_pinyin
[../pinyin_engine.c:24] context_obj: 0x5634a92acef0, sess: 94784185929936, msgtype: option, msg: _auto_commit
[../pinyin_engine.c:24] context_obj: 0x5634a92acef0, sess: 94784185929936, msgtype: option, msg: !ascii_mode
[../pinyin_engine.c:24] context_obj: 0x5634a92acef0, sess: 94784185929936, msgtype: schema, msg: luna_pinyin/朙月拼音
[../im.c:225] activate
```

So, what's next? What should I do to enter Chinese words? I'm using swaywm.

By the way, thank you for working on this project!

**Comment by xhebox** [comment]
You need to configure librime by your self first, just like other librime based IME. And a client that has adapt the new IME protocol: GTK3 is fine. I am using wlpinyin in firefox mainly.

Ctrl is the default key to toggle rime/english input. If you meet, I can give it a try.
