### ISSUE TITLE
wlpinyin does not work with Numlock on

### ISSUE THREAD

**Issue by cwz0522** [xhebox/wlpinyin#10]
It is not convenient that wlpinyin only work with Numlock=off. 

感謝你創建如此方便的專案，
我把原本gnome桌面下ibus+rime的設置直接搬進wlpinyin，
就能用上我原本配置好的嘸蝦米，讚的！

目前遇到的問題是
有時需要數字鍵盤時，需按下NumLock ，輸入完數字後，若沒再按NumLock讓它切回OFF態
使用wlpinyin就看到它會組字，但沒辦法輸出

想請教是我個人使用上的問題還是wlpinyin的限制？

**Comment by xhebox** [comment]
能多给几个例子吗? 尤其是日志.. 我手边没有小键盘能测试

```
meson --buildtype=debug ...
```

这样编译出来的二进制会打印日志.

**Comment by cwz0522** [comment]
我把中英切換改成左Shift
測試流程為:
1. 進入中文模式
2. z組字，空格鍵上字"整"
3. NumLock=on
4. t組字，空格沒上字
5. NumLock=off
6. 再按空格鍵，才上字"通"
[wlpinyin_debug.log](https://github.com/xhebox/wlpinyin/files/8925354/wlpinyin_debug.log)

**Comment by xhebox** [comment]
> 我把中英切換改成左Shift 測試流程為:
> 
>     1. 進入中文模式
> 
>     2. z組字，空格鍵上字"整"
> 
>     3. NumLock=on
> 
>     4. t組字，空格沒上字
> 
>     5. NumLock=off
> 
>     6. 再按空格鍵，才上字"通"
>        [wlpinyin_debug.log](https://github.com/xhebox/wlpinyin/files/8925354/wlpinyin_debug.log)

应该是空格映射错误了, 所以上字函数没被调用. 你有能力在

https://github.com/xhebox/wlpinyin/blob/45f4e68164ff4ac93d175a767f6693e0ecab5e08/im.c#L87

这个地方加个`wlpinyin_dbg`吗, 把`keysym`和`XKB_KEY_space`打印一下, 这一块`im_engine_candidate_choose`

https://github.com/xhebox/wlpinyin/blob/45f4e68164ff4ac93d175a767f6693e0ecab5e08/im.c#L114-L118

可能没有被调用.

**Comment by cwz0522** [comment]
加了，但只有在NumLock=off 時，才會運行到那一行，打印的結果如下:
keysym 57,  XKB_KEY_space 32

**Comment by xhebox** [comment]
> 加了，但只有在NumLock=off 時，才會運行到那一行，打印的結果如下: keysym 57, XKB_KEY_space 32

果然是映射错误了, 我看看怎么处理...

**Comment by xhebox** [comment]
@cwz0522 再用新的master试一试, 有bug的话附上日志

**Comment by cwz0522** [comment]
可以了，感謝！
