### ISSUE TITLE
Not working and getting ev_reset

### ISSUE THREAD

**Issue by gonced8** [xhebox/wlpinyin#11]
Hello, I think I followed the steps correctly, but I'm getting the following output:

	wlpinyin$ ./build/wlpinyin
	[../rime_engine.c:23] context_obj: 0x557f858769d0, sess: 0, msgtype: deploy, msg: start
	[../rime_engine.c:23] context_obj: 0x557f858769d0, sess: 0, msgtype: deploy, msg: success
	[../rime_engine.c:108] schema_name: 朙月拼音, id: luna_pinyin
	[../rime_engine.c:23] context_obj: 0x557f858769d0, sess: 94006189501488, msgtype: option, msg: _auto_commit
	[../rime_engine.c:23] context_obj: 0x557f858769d0, sess: 94006189501488, msgtype: option, msg: !ascii_mode
	[../rime_engine.c:23] context_obj: 0x557f858769d0, sess: 94006189501488, msgtype: option, msg: zh_trad
	[../rime_engine.c:23] context_obj: 0x557f858769d0, sess: 94006189501488, msgtype: option, msg: !zh_tw
	[../rime_engine.c:23] context_obj: 0x557f858769d0, sess: 94006189501488, msgtype: option, msg: !zh_simp
	[../rime_engine.c:23] context_obj: 0x557f858769d0, sess: 94006189501488, msgtype: schema, msg: luna_pinyin/朙月拼音
	[../im.c:308] ev_reset
	[../im.c:308] ev_reset
	[../im.c:308] ev_reset

And I'm unable to write in pinyin. Any idea about what might be the issue?
Thank you in advance!

**Comment by xhebox** [comment]
This is the reset handler, meaning your IME are actually working somehow. Any information about the application you are are running at? You know that I mentioned some application just does not support wlpinyin or wayland IME. You could try with gtk3 demos, which definitely support.

**Comment by gonced8** [comment]
I was running in Firefox. I'll try one of the demos.

**Comment by xhebox** [comment]
> I was running in Firefox. I'll try one of the demos.

FYI, use `left Control` to toggle between normal mode and pinyin mode. You should at least see some more logs like:

```
Dec 07 11:33:21 PC wlpinyin[767]: [../im.c:250] ev_key[BackSpace]: keycode 0e, keysym ff08, serial 1386, time 197646, released
Dec 07 11:33:21 PC wlpinyin[767]: [../im.c:173] upd_kbd[BackSpace]: keycode 0e, keysym ff08, released
Dec 07 11:33:21 PC wlpinyin[767]: [../im.c:250] ev_key[f]: keycode 21, keysym 66, serial 1388, time 197738, pressed
Dec 07 11:33:21 PC wlpinyin[767]: [../im.c:173] upd_kbd[f]: keycode 21, keysym 66, pressed
Dec 07 11:33:21 PC wlpinyin[767]: [../im.c:250] ev_key[f]: keycode 21, keysym 66, serial 1390, time 197833, released
Dec 07 11:33:21 PC wlpinyin[767]: [../im.c:173] upd_kbd[f]: keycode 21, keysym 66, released
Dec 07 11:33:22 PC wlpinyin[767]: [../im.c:250] ev_key[Return]: keycode 1c, keysym ff0d, serial 1392, time 197869, pressed
Dec 07 11:33:22 PC wlpinyin[767]: [../im.c:173] upd_kbd[Return]: keycode 1c, keysym ff0d, pressed
Dec 07 11:33:22 PC wlpinyin[767]: [../im.c:250] ev_key[Return]: keycode 1c, keysym ff0d, serial 1394, time 197958, released
Dec 07 11:33:22 PC wlpinyin[767]: [../im.c:173] upd_kbd[Return]: keycode 1c, keysym ff0d, released
```

**Comment by xhebox** [comment]
> Can confirm that it's not working for me in Firefox nor GTK3 demos... As for the logs, it doesn't react to the left Control press.

Which wayland env are you using? I doubt your compositor may have some problem on supporting IME protocols...

**Comment by gonced8** [comment]
Yup, it is sway. And don't worry, thank you for your help nonetheless.

**Comment by xhebox** [comment]
> Yup, it is sway. And don't worry, thank you for your help nonetheless.

Let me know if you have any progress. The only thing I can guess is that your sway is too old or so. Wlpinyin is not interacting correctly with the compositor: it did not even log key pressed by you!

**Comment by xhebox** [comment]
any news, or can I close the issue? @gonced8

**Comment by gonced8** [comment]
Sorry for not getting back. I didn't manage to make it work. Probably was a version being too old problem, since I was running Debian. Since then I've switched to Pop OS, so I won't be able to test it further. Thank you once again!
