### ISSUE TITLE
Environment variable settings?

### ISSUE THREAD

**Issue by taomaker** [xhebox/wlpinyin#13]
Got it working in foot but not GTK/QT applications. How to set below environment variables? Thanks.

GTK_IM_MODULE=???
QT_IM_MODULE=???
XMODIFIERS=@im=???

**Comment by xhebox** [comment]
> Got it working in foot but not GTK/QT applications. How to set below environment variables? Thanks.
> 
> GTK_IM_MODULE=??? QT_IM_MODULE=??? XMODIFIERS=@im=???

It is not a `GTK_IM_MODULE`, neither `QT_IM_MODULE`. And there is no support for X11, which means `XMODIFIERS` is not usable at all.

It only supports text-input-v3, which should have been supported by `gtk3`. I did not install QT, so I don't know.

If you can't use it on gtk apps, probably your GTK did not run with wayland backend. It is still running over X11. And wlpinyin is designed to work under pure wayland env, for my personal usage. It is not going to support X11 anyway.

**Comment by xhebox** [comment]
> > Got it working in foot but not GTK/QT applications. How to set below environment variables? Thanks.
> > GTK_IM_MODULE=??? QT_IM_MODULE=??? XMODIFIERS=@im=???
> 
> It is not a `GTK_IM_MODULE`, neither `QT_IM_MODULE`. And there is no support for X11, which means `XMODIFIERS` is not usable at all. You don't need to set any env.
> 
> It only supports text-input-v3, which should have been supported by `gtk3`. I did not install QT, so I don't know.
> 
> If you can't use it on gtk apps, probably your GTK did not run with wayland backend. It is still running over X11. And wlpinyin is designed to work under pure wayland env, for my personal usage. It is not going to support X11 anyway. Try `GDK_BACKEND=wayland`, maybe your gtk apps will work.

**Comment by xhebox** [comment]
Close since there is no response.
