### ISSUE TITLE
wlpinyin doesn't work in wlroots-0.17.1 + sway-1.9

### ISSUE THREAD

**Issue by cwz0522** [xhebox/wlpinyin#15]
您好，我使用Gentoo，最近upgrade後，發現wlpinyin無法使用了
排查結果為:

可工作版本: wlroots-0.16.2-r2 + sway-1.8.1-r2
無法工作版: wlroots-0.17.1 + sway-1.9

(sway 相依於 wlroots，所以沒辦法再細化拆解測試)
直接在 shel l執行 wlpinyin，可以看到組字沒問題，但就沒辦法上字，也沒錯誤訊息

**Comment by xhebox** [comment]
试试最新master，我在0.37.1下的hyprland测试成功了，是serial number的问题。

不过这个竟然真的有人用吗...？

**Comment by cwz0522** [comment]
應用最新的commit後，wlroots-0.17.1 + sway-1.9 也行了
感謝！
