### ISSUE TITLE
How to properly compile

### ISSUE THREAD

**Issue by omichaelo** [xhebox/wlpinyin#2]
Hello! I know this is a WIP and I am not a developer, but I really want to try `wlpinyin` (I, too, cannot find a properly working IME for wayland). I tried the following:
```
meson make
ninja -C make
./make/wlpinyin
```
I got the following:
```
[../pinyin_engine.c:24] context_obj: 0x55a5545a6aa0, sess: 0, msgtype: deploy, msg: start
[../pinyin_engine.c:24] context_obj: 0x55a5545a6aa0, sess: 0, msgtype: deploy, msg: failure
```
If you have time, can you tell me how to properly run `wlpinyin`? I will be grateful.

**Comment by xhebox** [comment]
I think you have compiled it successfully. It looks like that librime can not init itself successfully. You could concat me with qq:897002528 or wechat:xhebox. Can not really tell what is wrong with it. I can not reproduce.

**Comment by omichaelo** [comment]
The error is solved by properly putting rime configurations in ~/.config/wlpinyin
