### ISSUE TITLE
Is fireofx or Chromium still not Working?

### ISSUE THREAD

**Issue by Ttfios** [xhebox/wlpinyin#4]
I am using sway , and the chormium or firefox still not working. Is this have not implement yet ?

**Comment by xhebox** [comment]
Latest firefox does work. Chromium does not support yet.

BTW, it is intended for pure-wayland Apps. It does not work for xwayland Apps. Maybe you could start firefox like [the tutorial of archlinux](https://wiki.archlinux.org/title/Firefox#Wayland).

You could also test with `GDK_BACKEND=wayland gtk3-demo`, try the textbox in the demo.

**Comment by Ttfios** [comment]
> Latest firefox does work. Chromium does not support yet.
> 
> BTW, it is intended for pure-wayland Apps. It does not work for xwayland Apps. Maybe you could start firefox like [the tutorial of archlinux](https://wiki.archlinux.org/title/Firefox#Wayland).
> 
> You could also test with `GDK_BACKEND=wayland gtk3-demo`, try the textbox in the demo.

well, what's the compositor you are using?     i tried  firefox in wayland  and `GDK_BACKEND=wayland gtk3-demo` it just doesn't work, neither inputs or candidate, i think there is something different on compositors what effect the input_protocol .  i will try to figure this out.

**Comment by xhebox** [comment]
> well, what's the compositor you are using?

Sway I am using, https://github.com/xhebox/noname-linux/blob/master/ports/sway/Pkgfile
Gtk I am using, https://github.com/xhebox/noname-linux/blob/master/ports/gtk3/Pkgfile. Wayland patch in gtk is for firefox, don't bother it.

I guess you are still running gtk3 in xwayland or xorg.

**Comment by Ttfios** [comment]
Sorry, There are still some fcitx5 settings in my /etc/enviroments. After I comment these settings, everything works fine. I like the popup-windows design, thanks for your work.

**Comment by xhebox** [comment]
@Ttfios It is not a design. Sway did not implement the popup window, that is why it is in the candidate area. I may switch to a real popup window in the feature.

**Comment by Ttfios** [comment]
I know this and I still like it, if there is a IME runing like this , It will be pretty cool.
